"""
tests/test_signatures.py -- Regression tests for the YAML signature engine.

Verifies that the SignatureEngine produces the same detection results as the
original Python plugins for a set of fixture responses.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from lib.signature_loader import SignatureEngine, CompiledSignature, DetectionResult


SIGNATURES_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "signatures"
)


class TestSignatureLoading(unittest.TestCase):
    """Test that all YAML signatures load and compile without errors."""

    def setUp(self):
        self.engine = SignatureEngine(verbose=False)
        self.engine.load_builtin()

    def test_signatures_directory_exists(self):
        self.assertTrue(os.path.isdir(SIGNATURES_DIR))

    def test_signatures_loaded(self):
        """At least 100 signatures should load from the built-in directory."""
        self.assertGreaterEqual(self.engine.count, 100)

    def test_no_load_errors(self):
        """All signature files should load without errors."""
        errors = self.engine.get_load_errors()
        if errors:
            msg = "\n".join("  {}: {}".format(f, e) for f, e in errors[:10])
            self.fail("{} signature load errors:\n{}".format(len(errors), msg))

    def test_all_have_product_name(self):
        """Every loaded signature must have a non-empty product name."""
        for sig in self.engine.signatures:
            self.assertTrue(sig.product, "empty product in {}".format(sig.filepath))

    def test_no_duplicate_products(self):
        """No two signatures should have the same product name."""
        products = [sig.product for sig in self.engine.signatures]
        dupes = [p for p in products if products.count(p) > 1]
        self.assertEqual(len(dupes), 0, "duplicate products: {}".format(set(dupes)))


class TestSignatureDetection(unittest.TestCase):
    """Test detection logic against fixture responses."""

    def setUp(self):
        self.engine = SignatureEngine()
        self.engine.load_builtin()

    def test_cloudflare_detected_by_header(self):
        """Cloudflare should be detected when CF-RAY header is present."""
        results = self.engine.detect(
            content="<html>normal page</html>",
            headers={"CF-RAY": "7a1b2c3d4e5f6789-IAD", "Server": "cloudflare"},
            status=200,
        )
        products = [r.product for r in results]
        self.assertTrue(
            any("CloudFlare" in p or "Cloudflare" in p for p in products),
            "Cloudflare not detected. Got: {}".format(products)
        )

    def test_cloudflare_detected_by_body(self):
        """Cloudflare should be detected from body content."""
        results = self.engine.detect(
            content="<html><title>Attention required! | Cloudflare</title></html>",
            headers={"Server": "cloudflare"},
            status=403,
        )
        products = [r.product for r in results]
        self.assertTrue(
            any("CloudFlare" in p or "Cloudflare" in p for p in products),
            "Cloudflare not detected from body. Got: {}".format(products)
        )

    def test_modsecurity_detected(self):
        """ModSecurity should be detected from body markers."""
        results = self.engine.detect(
            content="<html><body>This error was generated by Mod_Security</body></html>",
            headers={},
            status=403,
        )
        products = [r.product for r in results]
        self.assertTrue(
            any("ModSecurity" in p or "Modsecurity" in p or "mod_security" in p.lower()
                for p in products),
            "ModSecurity not detected. Got: {}".format(products)
        )

    def test_no_false_positive_on_clean_page(self):
        """A normal page with no WAF indicators should not trigger detection."""
        results = self.engine.detect(
            content="<html><body><h1>Welcome</h1><p>Normal content here.</p></body></html>",
            headers={"Server": "nginx/1.24.0", "Content-Type": "text/html"},
            status=200,
        )
        # Allow at most low-confidence generic detections
        high_conf = [r for r in results if r.confidence == "high"]
        self.assertEqual(len(high_conf), 0,
                         "False positive high-confidence detections: {}".format(
                             [r.product for r in high_conf]))

    def test_akamai_detected(self):
        """Akamai should be detected from Server header."""
        results = self.engine.detect(
            content="<html>Access Denied</html>",
            headers={"Server": "AkamaiGHost"},
            status=403,
        )
        products = [r.product for r in results]
        self.assertTrue(
            any("Akamai" in p for p in products),
            "Akamai not detected. Got: {}".format(products)
        )

    def test_detect_first_returns_highest_confidence(self):
        """detect_first should return a result (short-circuit)."""
        result = self.engine.detect_first(
            content="<html>blocked by cloudflare</html>",
            headers={"Server": "cloudflare", "CF-RAY": "abc123-IAD"},
            status=403,
        )
        self.assertIsNotNone(result)
        self.assertIn("CloudFlare", result.product)

    def test_tamper_hints_available(self):
        """Detected signatures should provide tamper_hints for AdaptiveRanker."""
        result = self.engine.detect_first(
            content="<html>cloudflare</html>",
            headers={"Server": "cloudflare", "CF-RAY": "abc-IAD"},
            status=403,
        )
        self.assertIsNotNone(result)
        self.assertIsInstance(result.tamper_hints, list)


class TestCompiledSignature(unittest.TestCase):
    """Unit tests for CompiledSignature matching logic."""

    def _make_sig(self, data):
        data.setdefault("schema_version", 1)
        return CompiledSignature(data)

    def test_header_presence_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {"header_presence": ["X-Test-WAF"]},
        })
        self.assertTrue(sig.match("body", {"X-Test-WAF": "yes"}, 200))
        self.assertFalse(sig.match("body", {"Server": "nginx"}, 200))

    def test_pattern_body_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "patterns": [{"regex": r"blocked\s+by\s+testwaf", "fields": ["body"]}]
            },
        })
        self.assertTrue(sig.match("you have been blocked by TestWAF", {}, 403))
        self.assertFalse(sig.match("normal page", {}, 200))

    def test_pattern_header_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "patterns": [{"regex": "testwaf", "fields": ["server"]}]
            },
        })
        self.assertTrue(sig.match("", {"Server": "TestWAF/1.0"}, 200))
        self.assertFalse(sig.match("", {"Server": "nginx"}, 200))

    def test_contains_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "contains": [{"value": "twaf_id", "field": "set-cookie"}]
            },
        })
        self.assertTrue(sig.match("", {"Set-Cookie": "twaf_id=abc123"}, 200))
        self.assertFalse(sig.match("", {"Set-Cookie": "session=xyz"}, 200))

    def test_status_rule_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "status_rules": [{
                    "status": [403, 503],
                    "patterns": [{"regex": "testwaf", "fields": ["body"]}],
                }]
            },
        })
        self.assertTrue(sig.match("blocked by testwaf", {}, 403))
        self.assertFalse(sig.match("blocked by testwaf", {}, 200))

    def test_conditional_match(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "conditional": [{
                    "if_header": "X-Test-ID",
                    "patterns": [{"regex": "testwaf", "fields": ["body"]}],
                }]
            },
        })
        # Header present + body matches → detected
        self.assertTrue(sig.match("testwaf blocked", {"X-Test-ID": "123"}, 403))
        # Header absent → not detected even if body matches
        self.assertFalse(sig.match("testwaf blocked", {}, 403))

    def test_negate_pattern(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "patterns": [{"regex": "nginx", "fields": ["server"], "negate": True}]
            },
        })
        # Server is NOT nginx → negate pattern matches
        self.assertTrue(sig.match("", {"Server": "Apache"}, 200))
        # Server IS nginx → negate pattern does not match
        self.assertFalse(sig.match("", {"Server": "nginx"}, 200))

    def test_match_all_headers(self):
        sig = self._make_sig({
            "product": "TestWAF",
            "detection": {
                "match_all_headers": True,
                "patterns": [{"regex": "testwaf", "fields": ["all_headers"]}],
            },
        })
        self.assertTrue(sig.match("", {"X-Custom": "testwaf-active"}, 200))
        self.assertFalse(sig.match("", {"X-Custom": "nothing"}, 200))


if __name__ == "__main__":
    unittest.main()
