import os
import time
import json

import lib.settings
import lib.formatter

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WAFBypass Scan Report — {target}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }}
  .container {{ max-width: 1000px; margin: 0 auto; padding: 40px 20px; }}
  .header {{ text-align: center; padding: 60px 0 40px; border-bottom: 2px solid #30363d; margin-bottom: 40px; }}
  .header h1 {{ font-size: 2.2em; color: #58a6ff; margin-bottom: 8px; }}
  .header .subtitle {{ color: #8b949e; font-size: 1.05em; }}
  .header .version {{ color: #484f58; font-size: 0.85em; margin-top: 6px; }}
  .section {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 28px; margin-bottom: 24px; }}
  .section h2 {{ color: #58a6ff; font-size: 1.25em; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #21262d; }}
  .info-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
  .info-item {{ padding: 10px 14px; background: #0d1117; border-radius: 6px; border: 1px solid #21262d; }}
  .info-item .label {{ color: #8b949e; font-size: 0.8em; text-transform: uppercase; letter-spacing: 0.5px; }}
  .info-item .value {{ color: #c9d1d9; font-size: 1.05em; margin-top: 2px; word-break: break-all; }}
  .badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.82em; font-weight: 600; }}
  .badge-danger {{ background: #da363310; color: #f85149; border: 1px solid #f8514940; }}
  .badge-success {{ background: #3fb95010; color: #3fb950; border: 1px solid #3fb95040; }}
  .badge-warn {{ background: #d2992210; color: #d29922; border: 1px solid #d2992240; }}
  .badge-info {{ background: #58a6ff10; color: #58a6ff; border: 1px solid #58a6ff40; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th {{ text-align: left; padding: 10px 14px; background: #0d1117; color: #8b949e; font-weight: 600; font-size: 0.82em; text-transform: uppercase; border-bottom: 2px solid #30363d; }}
  td {{ padding: 10px 14px; border-bottom: 1px solid #21262d; font-family: 'Cascadia Code', 'Consolas', monospace; font-size: 0.9em; }}
  tr:hover {{ background: #1c2128; }}
  .tamper-example {{ color: #7ee787; }}
  .tamper-path {{ color: #8b949e; font-size: 0.82em; }}
  .timeline {{ position: relative; padding-left: 24px; }}
  .timeline::before {{ content: ''; position: absolute; left: 8px; top: 0; bottom: 0; width: 2px; background: #30363d; }}
  .timeline-item {{ position: relative; margin-bottom: 16px; padding-left: 24px; }}
  .timeline-item::before {{ content: ''; position: absolute; left: -20px; top: 6px; width: 10px; height: 10px; border-radius: 50%; background: #58a6ff; border: 2px solid #0d1117; }}
  .timeline-item .time {{ color: #484f58; font-size: 0.8em; }}
  .timeline-item .event {{ color: #c9d1d9; }}
  .code-block {{ background: #0d1117; border: 1px solid #21262d; border-radius: 6px; padding: 16px; overflow-x: auto; font-family: 'Cascadia Code', 'Consolas', monospace; font-size: 0.85em; margin-top: 8px; }}
  .footer {{ text-align: center; padding: 40px 0; color: #484f58; font-size: 0.82em; border-top: 1px solid #21262d; margin-top: 40px; }}
  .stat-card {{ display: inline-block; padding: 16px 24px; background: #0d1117; border-radius: 8px; border: 1px solid #21262d; margin: 6px; text-align: center; min-width: 100px; }}
  .stat-card .num {{ font-size: 1.8em; font-weight: 700; color: #58a6ff; }}
  .stat-card .lbl {{ font-size: 0.78em; color: #8b949e; margin-top: 4px; }}
  @media (max-width: 768px) {{ .info-grid {{ grid-template-columns: 1fr; }} }}
</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>WAFBypass Scan Report</h1>
    <div class="subtitle">{target}</div>
    <div class="version">Generated by WAFBypass v{version} | {timestamp}</div>
  </div>

  <div class="section">
    <h2>Summary</h2>
    <div style="display:flex;flex-wrap:wrap;gap:8px;">
      <div class="stat-card">
        <div class="num">{waf_count}</div>
        <div class="lbl">WAFs Detected</div>
      </div>
      <div class="stat-card">
        <div class="num">{tamper_count}</div>
        <div class="lbl">Working Bypasses</div>
      </div>
      <div class="stat-card">
        <div class="num">{payload_count}</div>
        <div class="lbl">Payloads Tested</div>
      </div>
      <div class="stat-card">
        <div class="num">{status_code}</div>
        <div class="lbl">Response Code</div>
      </div>
    </div>
    <div style="margin-top:16px;">
      <strong>Protection Status:</strong>
      {protection_badge}
      <strong style="margin-left:16px;">Web Server:</strong>
      <span class="badge badge-info">{webserver}</span>
    </div>
  </div>

  <div class="section">
    <h2>Target Information</h2>
    <div class="info-grid">
      <div class="info-item">
        <div class="label">Target URL</div>
        <div class="value">{target}</div>
      </div>
      <div class="info-item">
        <div class="label">Scan Time</div>
        <div class="value">{timestamp}</div>
      </div>
      <div class="info-item">
        <div class="label">Request Method</div>
        <div class="value">{method}</div>
      </div>
      <div class="info-item">
        <div class="label">Response Status</div>
        <div class="value">{status_code}</div>
      </div>
      <div class="info-item">
        <div class="label">Identified Web Server</div>
        <div class="value">{webserver}</div>
      </div>
      <div class="info-item">
        <div class="label">WAFBypass Version</div>
        <div class="value">v{version}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>WAF Detection Results</h2>
    {waf_section}
  </div>

  <div class="section">
    <h2>Working Bypass Techniques</h2>
    {tamper_section}
  </div>

  <div class="section">
    <h2>HTTP Response Headers</h2>
    {headers_section}
  </div>

  <div class="section">
    <h2>Scan Timeline</h2>
    <div class="timeline">
      {timeline_section}
    </div>
  </div>

  <div class="footer">
    <p>Generated by <strong>WAFBypass</strong> v{version} — Advanced WAF Detection &amp; Bypass Tool</p>
    <p>https://github.com/hnytgl/wafbypass</p>
  </div>

</div>
</body>
</html>"""


def generate_html_report(url, detected_wafs, working_tampers, headers_dict,
                         status_code, webserver, payload_count, method, timeline_events):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

    if detected_wafs:
        if isinstance(detected_wafs, str):
            detected_wafs = [detected_wafs]
        waf_count = len(detected_wafs)
        waf_list = "".join(
            '<tr><td>{}</td><td><span class="badge badge-danger">DETECTED</span></td></tr>'.format(w)
            for w in detected_wafs
        )
        protection_badge = '<span class="badge badge-danger">PROTECTED</span>'
    else:
        waf_count = 0
        waf_list = '<tr><td colspan="2" style="color:#8b949e;">No WAF detected</td></tr>'
        protection_badge = '<span class="badge badge-success">UNPROTECTED</span>'

    if working_tampers:
        tamper_count = len(working_tampers)
        tamper_rows = ""
        for desc, example, load_path in working_tampers:
            try:
                lp = str(load_path).split(" ")[1].replace("'", "")
            except IndexError:
                lp = str(load_path)
            tamper_rows += (
                '<tr>'
                '<td>{}</td>'
                '<td><code class="tamper-example">{}</code></td>'
                '<td><span class="tamper-path">{}</span></td>'
                '</tr>'
            ).format(desc, example[:120], lp)
        tamper_section = (
            '<table><thead><tr><th>Technique</th><th>Example Payload</th><th>Load Path</th></tr></thead>'
            '<tbody>{}</tbody></table>'.format(tamper_rows)
        )
    else:
        tamper_count = 0
        tamper_section = '<p style="color:#8b949e;">No working bypass techniques found.</p>'

    if headers_dict:
        header_rows = ""
        for key, value in sorted(headers_dict.items()):
            header_rows += '<tr><td><strong>{}</strong></td><td>{}</td></tr>'.format(key, str(value)[:200])
        headers_section = (
            '<table><thead><tr><th>Header Name</th><th>Value</th></tr></thead>'
            '<tbody>{}</tbody></table>'.format(header_rows)
        )
    else:
        headers_section = '<p style="color:#8b949e;">No HTTP headers captured.</p>'

    timeline_html = ""
    for i, evt in enumerate(timeline_events):
        timeline_html += (
            '<div class="timeline-item">'
            '<div class="time">{}</div>'
            '<div class="event">{}</div>'
            '</div>'
        ).format(evt["time"], evt["event"])

    html = HTML_TEMPLATE.format(
        target=url,
        version=lib.settings.VERSION,
        timestamp=timestamp,
        waf_count=waf_count,
        tamper_count=tamper_count,
        payload_count=payload_count,
        status_code=status_code,
        webserver=webserver or "Unknown",
        method=method,
        protection_badge=protection_badge,
        waf_section=(
            '<table><thead><tr><th>Firewall Name</th><th>Status</th></tr></thead>'
            '<tbody>{}</tbody></table>'.format(waf_list)
        ),
        tamper_section=tamper_section,
        headers_section=headers_section,
        timeline_section=timeline_html,
    )

    return html


def save_html_report(url, detected_wafs, working_tampers, headers_dict,
                     status_code, webserver, payload_count, method, timeline_events,
                     output_dir=None):
    html = generate_html_report(
        url, detected_wafs, working_tampers, headers_dict,
        status_code, webserver, payload_count, method, timeline_events
    )

    if output_dir is None:
        output_dir = lib.settings.HOME

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    safe_name = url.replace("https://", "").replace("http://", "").replace("/", "_").replace(":", "_")[:60]
    filename = "wafbypass_report_{}_{}.html".format(
        safe_name, time.strftime("%Y%m%d_%H%M%S")
    )
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return filepath
