import re

from lib.settings import HTTP_HEADER

__product__ = "AWS WAF v2 (Amazon Web Services)"


def detect(content, **kwargs):
    headers = kwargs.get("headers", {})
    content = str(content)
    detection_schemas = (
        re.compile(r"awselb/.+", re.I),
        re.compile(r"x-amzn-requestid", re.I),
        re.compile(r"x-amz-id-\d+", re.I),
        re.compile(r"x-amz-request-id", re.I),
        re.compile(r"request has been blocked", re.I),
        re.compile(r"aws.waf", re.I),
    )
    server = headers.get(HTTP_HEADER.SERVER, "")
    x_amzn = headers.get("X-Amzn-RequestId", "")
    x_cache = headers.get(HTTP_HEADER.X_CACHE, "")

    if x_amzn:
        for detection in detection_schemas:
            if detection.search(content) is not None:
                return True
            if detection.search(server) is not None:
                return True
        if "403 forbidden" in content.lower() and "x-amzn-requestid" in str(headers).lower():
            return True
        if "error from gateway" in content.lower() or "generated by aws" in content.lower():
            return True

    # Check for AWS ALB/NLB + WAF integration
    via_header = headers.get(HTTP_HEADER.VIA, "")
    if "awselb" in str(via_header).lower() and "error" in content.lower() and "403" in str(kwargs.get("status", "")):
        return True

    return False
